---
title: "Benchmarking"
output: html_document
date: "2025-10-15"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
library(Signac)
library(Seurat)
library(GenomeInfoDb)
library(EnsDb.Hsapiens.v86)
library(ggplot2)
library(patchwork)
library(ggrepel)
library(dplyr)
```

```{r}
##Load genes annotations from Ensembl 
annotations = GetGRangesFromEnsDb(ensdb = EnsDb.Hsapiens.v86)
annotations = renameSeqlevels(annotations, mapSeqlevels(seqlevels(annotations), "UCSC"))
genome(annotations) = "hg38"
head(annotations)
counts <- Read10X_h5(filename = "/Users/lucascortes/Documents/Pickett/Mike_Keogh/Data/241121-PBMC_results_masked/filtered_peak_bc_matrix.h5")
metadata <- read.csv(
  file = "/Users/lucascortes/Documents/Pickett/Mike_Keogh/Data/241121-PBMC_results_masked/singlecell.csv",
  header = TRUE,
  row.names = 1
)

assay <- CreateChromatinAssay(
  counts = counts,
  sep = c(":", "-"),
  annotation = annotations,
  min.cells = 5,
  genome = "hg38",
  fragments = file.path("/Users/lucascortes/Documents/Pickett/Mike_Keogh/Data/241121-PBMC_results_masked/fragments.tsv.gz") # TSV MUST be bgzipped
)

seurat <- CreateSeuratObject(counts = assay, assay = 'peaks')
```
```{r}
##Craete Seurat object 
seurat = CreateSeuratObject(counts = assay,
                            assay = 'peaks',
                            meta.data = metadata)
seurat
```
```{r}
# Augment QC metrics computed by cellranger-atac
seurat$pct_reads_in_peaks = seurat$peak_region_fragments / seurat$passed_filters * 100
# Compute TSS enrichment score and nucleosome banding pattern
seurat = TSSEnrichment(seurat)
seurat = NucleosomeSignal(seurat)
#Visualise QC metrics for each cell
VlnPlot(seurat, c("TSS.enrichment", "nCount_peaks", "nucleosome_signal", 
        "pct_reads_in_peaks"), pt.size = 0, ncol = 2)
```
```{r}
##Subsetting:

seurat <- subset(
  x = seurat,
  subset = nCount_peaks > 1000 & nCount_peaks < 50000 &
           pct_reads_in_peaks > 20 & TSS.enrichment > 3 & nucleosome_signal < 4
)
seurat

## Stricter subset for bonsai
seurat_stricter <- subset(
  x = seurat,
  subset = nCount_peaks > 3000 & nCount_peaks < 100000 &
           pct_reads_in_peaks > 30 & TSS.enrichment > 5 & nucleosome_signal < 4
)
seurat_stricter

# Extract counts matrix from peaks assay (sparse)
counts <- GetAssayData(seurat_stricter, assay = "peaks", slot = "counts")

# Convert sparse matrix to dense matrix
counts_mat <- as.matrix(counts)

# Convert to data frame, with gene/peak names as a separate column
counts_df <- data.frame(
  peak = rownames(counts_mat),  # rownames are peak names
  counts_mat,
  check.names = FALSE,
  row.names = NULL
)

# Write to TSV (no row names, peak names as first column)

```
```{r}

### Integrate Mitochondrial Variant Data

mem.maxVSize(50000)
mito.data <- ReadMGATK(dir = file.path( "/Users/lucascortes/Documents/Pickett/Mike_Keogh/Data/241121-PBMC_results_masked/final/"))
#Calculate average depth

avgMitoDepth = mean(mito.data[["depth"]][["mito.depth"]], na.rm = TRUE)


mito <- CreateAssayObject(counts = mito.data$counts)

mito <- subset(mito, cells = colnames(seurat))

seurat[["mito"]] = mito
seurat <- AddMetaData(seurat, metadata = mito.data$depth, col.name = "mtDNA_depth")

##Filter out NAs (there's lots of them) and plot
seurat_filtered <- subset(seurat, subset = !is.na(mtDNA_depth))
VlnPlot(seurat_filtered, features = "mtDNA_depth", pt.size = 0)

## Look at standard deviation of depth
sd(seurat_filtered$mtDNA_depth)

# Extract the data as a data frame
depth_df <- FetchData(seurat_filtered, vars = "mtDNA_depth")

# Plot histogram
ggplot(depth_df, aes(x = mtDNA_depth)) +
  geom_histogram(binwidth = 5, fill = "steelblue", color = "black") +
  xlim(0, 100) +
  labs(title = "Histogram of mtDNA Depth",
       x = "mtDNA Depth",
       y = "Number of Cells") +
  theme_minimal()

```
```{r}
seuratmTDNA <- subset(seurat, mtDNA_depth >0)
### Signac workflow: Dimensional Reduction & Clustering
seuratmTDNA <- RunTFIDF(seuratmTDNA)
seuratmTDNA <- FindTopFeatures(seuratmTDNA, min.cutoff = 3) ##Changed from 10
seuratmTDNA <- RunSVD(seuratmTDNA)
seuratmTDNA <- RunUMAP(seuratmTDNA, reduction = "lsi", dims = 2:50, n.neighbors = 10, min.dist = 0.1, spread = 10 )
seuratmTDNA <- FindNeighbors(seuratmTDNA, reduction = "lsi", dims = 2:50)
seuratmTDNA <- FindClusters(seuratmTDNA, resolution = 0.5, algorithm = 3)

DimPlot(seuratmTDNA , label = TRUE) + NoLegend() #+ scale_color_manual(values = c("#6666CC", "#CCCCFF", "#b37bb3", "#82032d", "#e05b02", "#e8ba02", "#669900"))
```

```{r}
library(dplyr)
### Identify Mitochondrial Variants & Clonotypes
variable.sites <- IdentifyVariants(seuratmTDNA, assay = "mito", refallele = mito.data$refallele)
base_sites = filter(variable.sites, n_cells_conf_detected >=1)
base_sites_export = base_sites$variant
write.csv(base_sites_export, file="/Users/lucascortes/Library/CloudStorage/OneDrive-Personal/Documents/Work/Pickett/Mike_Keogh/analysis/PBMC_Surgical/PBMC_surgical_variants_mgatk.csv")
VariantPlot(variants =variable.sites)



high.conf <- subset(
  variable.sites, subset = n_cells_conf_detected >= 5 &
    strand_correlation >= 0.65 & vmr > 0.01
)

n_cells_conf = high.conf$n_cells_conf_detected
mean(n_cells_conf)
median(n_cells_conf)


```

```{r}
seuratmTDNA <- AlleleFreq(
  object = seuratmTDNA,
  variants = high.conf$variant,
  assay = "mito"
)
seuratmTDNA[["alleles"]]

DefaultAssay(seuratmTDNA) <- "alleles"
alleles.view <- c(rownames(high.conf))

top_alleles <- rownames(high.conf)[1:20]
FeaturePlot(seuratmTDNA, features = top_alleles, order = TRUE,
            cols = c("grey", "darkred"), ncol = 5) & NoLegend()

```

```{r}
seuratmTDNA <- AlleleFreq(
  object = seuratmTDNA,
  variants = high.conf$variant,
  assay = "mito"
)
seuratmTDNA[["alleles"]]

DefaultAssay(seuratmTDNA) <- "alleles"
alleles.view <- c(rownames(high.conf))

top_alleles <- rownames(high.conf)[1:20]
FeaturePlot(seuratmTDNA, features = top_alleles, order = TRUE,
            cols = c("grey", "darkred"), ncol = 5) & NoLegend()

```

```{r}
crc <- AlleleFreq(
  object = seuratmTDNA,
  variants = high.conf$variant,
  assay = "mito"
)
crc[["alleles"]]
```


```{r}
DefaultAssay(crc) <- "alleles"
crc <- FindClonotypes(crc)
DoHeatmap(crc, features = VariableFeatures(crc), slot = "data", disp.max = 0.1) +
  scale_fill_viridis_c()

```

